// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4t_3FmqnGJy3Rl6FqEN7yTqrEysr-ZAs',
    appId: '1:880717541569:web:2eb4de760b64e2a76b6440',
    messagingSenderId: '880717541569',
    projectId: 'thanush-6b5e8',
    authDomain: 'thanush-6b5e8.firebaseapp.com',
    databaseURL: 'https://thanush-6b5e8-default-rtdb.firebaseio.com',
    storageBucket: 'thanush-6b5e8.appspot.com',
    measurementId: 'G-DKZLM8EDYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4PpuWN2pA9kqWKvWtoGAFbEONZ8UZYA',
    appId: '1:58548553120:android:c129e1fd7d65f7b7fb50c5',
    messagingSenderId: '58548553120',
    projectId: 'studentfoodservice-82f3b',
    databaseURL: 'https://studentfoodservice-82f3b-default-rtdb.firebaseio.com',
    storageBucket: 'studentfoodservice-82f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUNLLYqbH8hvb9D-zQaptW_RQVbpxXKQ',
    appId: '1:910225285466:ios:e5a09f33489c7b356b1363',
    messagingSenderId: '910225285466',
    projectId: 'blockchaintender-6a9b0',
    databaseURL: 'https://blockchaintender-6a9b0-default-rtdb.firebaseio.com',
    storageBucket: 'blockchaintender-6a9b0.firebasestorage.app',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUNLLYqbH8hvb9D-zQaptW_RQVbpxXKQ',
    appId: '1:910225285466:ios:e5a09f33489c7b356b1363',
    messagingSenderId: '910225285466',
    projectId: 'blockchaintender-6a9b0',
    databaseURL: 'https://blockchaintender-6a9b0-default-rtdb.firebaseio.com',
    storageBucket: 'blockchaintender-6a9b0.firebasestorage.app',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4t_3FmqnGJy3Rl6FqEN7yTqrEysr-ZAs',
    appId: '1:880717541569:web:366a7535775dd48b6b6440',
    messagingSenderId: '880717541569',
    projectId: 'thanush-6b5e8',
    authDomain: 'thanush-6b5e8.firebaseapp.com',
    databaseURL: 'https://thanush-6b5e8-default-rtdb.firebaseio.com',
    storageBucket: 'thanush-6b5e8.appspot.com',
    measurementId: 'G-PFLYQ6RHT0',
  );

}